[package]
name = "runtime-common"
version = "1.0.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
edition = "2018"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"

[dependencies]
# Substrate dependencies
node-primitives = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-api = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }

# Local Dependencies
pallet-anchors = { path = "../../pallets/anchors", default-features = false }


[features]
default = ["std"]
std = [
    "node-primitives/std",
    "pallet-anchors/std",
    "sp-api/std",
]
on-chain-release-build = [
    "sp-api/disable-logging",
]
