[package]
authors = ['buterajay@protonmail.com']
description = 'Access control list for bridge paths across chains'
edition = '2018'
license = "LGPL-3.0"
name = 'pallet-bridge-mapping'
repository = "https://github.com/centrifuge/centrifuge-chain/pallets/bridge-mapping"
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '2.0.0', features = ['derive'] , default-features = false }

frame-support = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }

[dev-dependencies]
sp-core = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std'
]
