[package]
name = 'pallet-bridge'
description = 'Bridge pallet'
authors = ['The Centrifugians Tribe']
edition = '2018'
homepage = 'https://centrifuge.io'
license = "LGPL-3.0"
repository = 'https://github.com/centrifuge/centrifuge-chain'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# Substrate basic primitives
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
sp-core = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
sp-std = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master" }

# Centrifuge Chain dependencies
chainbridge = { git = "https://github.com/centrifuge/chainbridge-substrate.git", default-features = false, branch = "master" }
pallet-bridge-mapping = { path = "../bridge-mapping", default-features = false }
pallet-fees = { path = "../fees", default-features = false }
pallet-nft = { path = "../nft", default-features = false }
runtime-common = { path = "../../runtime/common", default_features = false }
unique-assets = { git = "https://github.com/centrifuge/unique-assets", default-features = false, branch = "master" }


[dev-dependencies]
# Testing/mocking dependencies
chainbridge = { git = "https://github.com/centrifuge/chainbridge-substrate.git", default-features = false, branch = "master" }
node-primitives = { git = "https://github.com/centrifuge/substrate",  default-features = false, branch = "master" }
pallet-anchors = { path = "../anchors", default-features = false }
pallet-fees = { path = "../fees", default-features = false }
pallet-bridge-mapping = { path = "../bridge-mapping", default-features = false }
pallet-registry = { path = "../registry", default-features = false }
pallet-authorship = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
pallet-timestamp = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }
proofs = { path = "../../libs/proofs", default-features = false }
sp-core = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master"  }
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate.git", default-features = false, branch = "master" }

[features]
default = ['std']
std = [
    'chainbridge/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-balances/std',
    'pallet-bridge-mapping/std',
    'pallet-fees/std',
    'pallet-nft/std',
    'runtime-common/std',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
    'unique-assets/std',
]
